// Code generated by goctl. DO NOT EDIT.
package types

type AliVideoCallBackReq struct {
	EventType   string              `json:"eventType"`   // 事件类型
	UserId      int64               `json:"userId"`      // 用户ID
	EventTime   string              `json:"eventTime"`   // 事件产生时间（UTC时间），格式为yyyy-MM-ddTHH:mm:ssZ
	MessageBody CallbackMessageBody `json:"messageBody"` // 消息体
}

type AliVideoCallBackRes struct {
	Status       bool   `json:"status"` // 视频剪辑合成回调操作数据库响应
	ErrorMessage string `json:"status"` // 视频剪辑合成回调操作数据库响应信息
}

type ApiTemplateListData struct {
	Id   int64  `json:"id,optional"`   // 模板id 单次请求传入
	Name string `json:"name,optional"` // 模版名称
}

type BgmClassList struct {
	Id   int64  `json:"id"`   // bgmid
	Name string `json:"name"` // bgm分类名称
}

type CallbackMessageBody struct {
	Status       string `json:"status"`       // 任务状态
	MediaURL     string `json:"mediaUrl"`     // 云剪辑成片地址
	MediaId      string `json:"mediaId"`      // 云剪辑成片媒资ID
	ProjectId    string `json:"projectId"`    // 云剪辑工程ID
	ErrorCode    string `json:"errorCode"`    // 云剪辑错误码
	ErrorMessage string `json:"errorMessage"` // 云剪辑错误信息
	JobId        string `json:"jobId"`        // 云剪辑任务ID
	EventTime    string `json:"eventTime"`
	EventType    string `json:"eventType"`
}

type GetBgmClassListRes struct {
	Data  BgmClassList `json:"data"`  // list
	Count int64        `json:"count"` // 	总数
}

type GetBgmListReq struct {
	ClassId int64 `form:"classId"` // 分类id，不传获取所有分类的
	Page    int64 `json:"page"`    // 分页，默认第一页
}

type GetBgmListRes struct {
	Data  BgmClassList `json:"data"`  // list
	Count int64        `json:"count"` // 	总数
}

type GetTaskSnRes struct {
	TaskSn     string `json:"TaskSn,optional"`     // 流水号
	IsProgress bool   `json:"IsProgress,optional"` // 是否是正在生成中的
}

type GetTaskVideoListData struct {
	UserTemplateId int64  `json:"userTemplateId"` // 用户使用的模板，批量生成时使用
	VideoUrl       string `json:"videoUrl"`       // 视频url
	CoverUrl       string `json:"coverUrl"`       //封面url
	Size           int64  `json:"size"`           // 大小
	Duration       int64  `json:"duration"`       // 视频长度
}

type GetTaskVideoListReq struct {
	TaskSn string `form:"taskSn"` // 流水号
}

type GetTaskVideoListRes struct {
	TaskSn      string               `json:"taskSn"`              // taskSn
	AlsoCount   int32                `json:"IsProgress,optional"` // 还剩多少条
	ChangeCount int32                `json:"NuLimit,optional"`    // 换一个可以换的次数
	IsChange    bool                 `json:"NuLimit,optional"`    // 是否有正在生成中
	BatchNumber int32                `json:"batchNumber""`        // 批量生成最大条数
	Data        GetTaskVideoListData `json:"NuLimit,optional"`    // list
}

type GetTaskVideoStatusReq struct {
	TaskSn string `json:"TaskSn,optional"` // 流水号
}

type GetTaskVideoStatusRes struct {
	TaskSn       string `json:"TaskSn,optional"`       // 流水号
	Status       int32  `json:"status,optional"`       // 生成状态 1已发起视频生成 2处理中 3处理完成成功 4处理完成失败 5部分成功部分失败 6任务不存在
	VideoCount   int32  `json:"videoCount,optional"`   // 生成视频数量
	SuccessCount int32  `json:"successCount,optional"` // 成功数量
}

type GetTemplateListRes struct {
	Data           ApiTemplateListData `json:"TaskSn,optional"`     // 流水号
	IsSellingPoint int32               `json:"IsProgress,optional"` // 0未知 1生成 2不生成
}

type VideoBatchReq struct {
	TaskSn         string `form:"taskSn"`         // 生成视频任务流水号
	UserTemplateId int64  `form:"userTemplateId"` // 用户模板id
	LibraryId      int64  `form:"libraryId"`      // 成品库id
	Number         int64  `form:"number"`         // 生成数量
}

type VideoBatchRes struct {
	Status int32 `json:"status"` // 返回状态 1成功
}

type VideoChangeReq struct {
	TaskSn string `form:"taskSn"` // 生成视频任务流水号
}

type VideoChangeRes struct {
	Status int32 `json:"status"` // 返回状态 1成功
}

type VideoPreviewReq struct {
	TaskSn                string  `form:"taskSn"`                  // 生成视频任务流水号
	VideoType             int32   `form:"videoType"`               // 视频生成类型，默认1， 1ai生成，2固定文案，3无文案
	TemplateId            int64   `form:"templateId,optional"`     // 模板标签id
	IsSellingPoint        int64   `form:"isSellingPoint,optional"` // 是否生成花字卖点 1生成 2不生成
	VideoIds              []int64 `form:"videoIds"`                // 视频ids
	BgmIds                []int64 `form:"bgmIds"`                  // 背景音乐ids
	CopyWritingIds        []int64 `form:"copyWritingIds"`          // 脚本ids
	SellingPointIds       []int64 `form:"sellingPointIds"`         // 自定义卖点文案ids
	RegularCopyWritingIds []int64 `form:"regularCopyWritingIds"`   // 固定文案ids
}

type VideoPreviewRes struct {
	Status int32 `json:"status"` // 返回状态 1成功
}
